//flutter
import 'package:flutter/widgets.dart' show IconData;

import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final Map<String, IconData> icons = {
  'bolt': FontAwesomeIcons.bolt,
  'book': FontAwesomeIcons.book,
  'bookmark': FontAwesomeIcons.bookmark,
  'certificate': FontAwesomeIcons.certificate,
  'check': FontAwesomeIcons.check,
  'cross': FontAwesomeIcons.cross,
  'clock': FontAwesomeIcons.clock,
  'cog': FontAwesomeIcons.cog,
  'exclamation': FontAwesomeIcons.exclamation,
  'eye': FontAwesomeIcons.eye,
  'film': FontAwesomeIcons.film,
  'gamepad': FontAwesomeIcons.gamepad,
  'globe': FontAwesomeIcons.globe,
  'heart': FontAwesomeIcons.heart,
  'lock': FontAwesomeIcons.lock,
  'music': FontAwesomeIcons.music,
  'road': FontAwesomeIcons.road,
  'search': FontAwesomeIcons.search,
  'star': FontAwesomeIcons.star,
  'thumbs-up': FontAwesomeIcons.thumbsUp,
  'thumbs-down': FontAwesomeIcons.thumbsDown,
  'thumb-tack': FontAwesomeIcons.thumbtack,
  'smile': FontAwesomeIcons.smile,
  'meh': FontAwesomeIcons.meh,
  'frown': FontAwesomeIcons.frown,
  'trash': FontAwesomeIcons.trash,
  'user': FontAwesomeIcons.user,
  'youtube': FontAwesomeIcons.youtube,
  'fa-bolt': FontAwesomeIcons.bolt,
  'fa-book': FontAwesomeIcons.book,
  'fa-bookmark': FontAwesomeIcons.bookmark,
  'fa-certificate': FontAwesomeIcons.certificate,
  'fa-check': FontAwesomeIcons.check,
  'fa-cross': FontAwesomeIcons.cross,
  'fa-clock-o': FontAwesomeIcons.clock,
  'fa-cog': FontAwesomeIcons.cog,
  'fa-exclamation': FontAwesomeIcons.exclamation,
  'fa-eye': FontAwesomeIcons.eye,
  'fa-film': FontAwesomeIcons.film,
  'fa-gamepad': FontAwesomeIcons.gamepad,
  'fa-globe': FontAwesomeIcons.globe,
  'fa-heart': FontAwesomeIcons.heart,
  'fa-lock': FontAwesomeIcons.lock,
  'fa-music': FontAwesomeIcons.music,
  'fa-road': FontAwesomeIcons.road,
  'fa-search': FontAwesomeIcons.search,
  'fa-star': FontAwesomeIcons.star,
  'fa-thumbs-up': FontAwesomeIcons.thumbsUp,
  'fa-thumbs-down': FontAwesomeIcons.thumbsDown,
  'fa-thumb-tack': FontAwesomeIcons.thumbtack,
  'fa-smile': FontAwesomeIcons.smile,
  'fa-meh': FontAwesomeIcons.meh,
  'fa-frown-o': FontAwesomeIcons.frown,
  'fa-trash': FontAwesomeIcons.trash,
  'fa-user': FontAwesomeIcons.user,
  'fa-youtube': FontAwesomeIcons.youtube,
};
